name: Update Map

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - 'faculty.csv'
  schedule:
  - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install library
        run: pip install git+https://github.com/cmccomb/map-of-research.git
      - name: scrape the data
        run: scrape_faculty_data
      - name: commit and push changes
        uses: actions-js/push@master