name: update visualization

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["update data"]
    types:
      - completed
  push:
    branches: [ main ]
    paths:
      - 'data/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  full_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install library
        run: pip install git+https://github.com/cmccomb/map-of-research.git
      - name: create the visualization
        run: visualize_faculty_data
      - name: commit and push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
