name: Update Map for Faculty Group 1

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths:
      - 'faculty.csv'
  schedule:
  - cron: "0 0 7 * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: move faculty csv into place
        run: pwd
      - name: move faculty csv into place
        run: ls
  call-workflow-passing-data:
    uses: cmccomb/map-of-research/.github/workflows/update.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
